server.port=8084

spring.application.name=ms-auth
spring.datasource.url=jdbc:postgresql://localhost:5436/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=dad-upeu-microservicios-jwt-secret-key-2026-super-segura-0123456789
jwt.expiration-ms=3600000

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

management.endpoints.web.exposure.include=health,info
