server.port=8082
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5439}/${DB_NAME:alumno_db}
spring.datasource.username=alumno_user
spring.datasource.password=alumno_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=dad-upeu-microservicios-jwt-secret-key-2026-super-segura-0123456789
